获取订单详情={
    result=0,
    data={
        wechat_param={
            partnerid=1320624401,
            total_fee=0.01,
            package=Sign=WXPay,
            noncestr=ChRBqZMMUqqgJ8JX,
            timestamp=1458739580,
            prepayid=wx20160323212620181876ee4a0274103199,
            sign=C8467BF164749148112D6152811AFD6C
        },
        order_detail={
            orderDetailList=[
            {
                goodsPic=http://static.exinetian.com/b2v/goods/image/source/2016322/1458631506539023.jpg,
                frontPrice=0.01,
                frontQuantity=1,
                goodsId=1005,
                frontWeight=100,
                goodsName=测试代下单
            }
                             ],
            orderHeader={
                id=849,
                buyerRemark=1,
                orderCode=OD20160323210965,
                payMode=WC,
                address=某市某镇某街道某市场,
                paymentAmount=0.01,
                buyerReceiveTime=<null>,
                createTime=2016-03-23 21:15:04,
                consigneeTel1=13245678912,
                marketName=A测试市场,
                businessStatus=0,
                marketId=58
            }
        }
    }
}


获取所有订单为 {
    result=0,
    data={
        order_list=[
        {
            orderDetailList=[
            {
                goodsPic=http://static.exinetian.com/b2v/goods/image/source/2016322/1458631506539023.jpg,
                frontPrice=0.01,
                frontQuantity=1,
                goodsId=1005,
                frontWeight=100,
                goodsName=测试代下单
            }
                             ],
            orderHeader={
                id=849,
                parentId=-1,
                businessStatusName=待付款,
                buyerRemark=1,
                orderCode=OD20160323210965,
                payMode=WC,
                address=某市某镇某街道某市场,
                paymentAmount=0.01,
                consigneeTel1=13245678912,
                marketName=A测测试代下单
            }
            ],
            orderHeader={
                id=849,
                parentId=-1,
                businessStatusName=待付款,
                buyerRemark=1,
                orderCode=OD20160323210965,
                payMode=WC,
                address=某市某镇某街道某市场,
                paymentAmount=0.01,
                consigneeTel1=13245678912,
                marketName=A测\350试市场,
                isParent=1,
                businessStatus=0,
                marketId=58
            }
        },
        {
            orderDetailList=[
            {
                goodsPic=http://static.exinetian.com/b2v/goods/image/source/2016323/1458715606488057.jpg,
                frontPrice=57,
                frontQuantity=1,
                goodsId=1009,
                frontWeight=23,
                goodsName=测试代下单
            }
                             ],
            orderHeader={
                id=849,
                parentId=-1,
                businessStatusName=待付款,
                buyerRemark=1,
                orderCode=OD20160323210965,
                payMode=WC,
                address=某市某镇某街道某市场,
                paymentAmount=0.01,
                consigneeTel1=13245678912,
                marketName=A测\350试市场,
                isParent=1,
                businessStatus=0,
                marketId=58
            }
        },
        {
            orderDetailList=[
            {
                goodsPic=http://static.exinetian.com/b2v/goods/image/source/2016323/1458715606488057.jpg,
                frontPrice=57,
                frontQuantity=1,
                goodsId=1009,
                frontWeight=23,
                goodsName=\345小白兔a 
            }
                             ],
            orderHeader={
                id=848,
                parentId=847,
                businessStatusName=待发货,
                buyerRemark=1,
                orderCode=OD20160323200964,
                payMode=BA,
                address=某市某镇某街道某市场,
                paymentAmount=57,
                consigneeTel1=13245678912,
                marketName=A测试市场,
                isParent=0,
                businessStatus=2,
                marketId=58
            }
        },
        {
            orderDetailList=[
            {
                goodsPic=http://static.exinetian.com/b2v/goods/image/source/2016323/1458715606488057.jpg,
                frontPrice=57,
                frontQuantity=1,
                goodsId=1009,
                frontWeight=23,
                goodsName=小白兔a 
            }
                             ],
            orderHeader={
                id=846,
                parentId=845,
                businessStatusName=待发货,
                buyerRemark=1,
                orderCode=OD20160323200962,
                payMode=BA,
                address=某市某镇某街道某市场,
                paymentAmount=57,
                consigneeTel1=13245678912,
                marketName=A测试市场,
                isParent=0,
                businessStatus=2,
                marketId=58
            }
        },
        {
            orderDetailList=[
            {
                goodsPic=http://static.exinetian.com/b2v/goods/image/source/2016323/1458715606488057.jpg,
                frontPrice=57,
                frontQuantity=1,
                goodsId=1009,
                frontWeight=23,
                goodsName=小白兔a 
            }
                             ],
            orderHeader={
                id=844,
                parentId=843,
                businessStatusName=待发货,
                buyerRemark=1,
                orderCode=OD20160323200960,
                payMode=BA,
                address=某市某镇某街道某市场,
                paymentAmount=57,
                consigneeTel1=13245678912,
                marketName=A测试市场,
                isParent=0,
                businessStatus=2,
                marketId=58
            }
        },